# _   _            ____                      _               _
#| \ | | ___ _   _| __ ) _ __ ___   __ _  __| | ___ __ _ ___| |_
#|  \| |/ _ \ | | |  _ \| '__/ _ \ / _` |/ _` |/ __/ _` / __| __|
#| |\  |  __/ |_| | |_) | | | (_) | (_| | (_| | (_| (_| \__ \ |_
#|_| \_|\___|\__, |____/|_|  \___/ \__,_|\__,_|\___\__,_|___/\__|
#            |___/

# Разработчик - https://t.me/NeyOff
# Права: ney_broadcast.ad, ney_broadcast.buy, ney_broadcast.bc

# Общие сообщения (глобальные для всех команд)
messages:
  no_console: "&cЭту команду можно использовать только от имени игрока!"
  no_permission: "&cУ вас нет прав на использование этой команды!"
  contains_color_code: "&cНельзя использовать символы & или § в сообщении!"
  too_large: "&cСообщение не должно быть более {length} симв."

# Настройки для каждой команды
commands:

  bc:

    # Право доступа
    permission: "ney_broadcast.bc"
    # Максимальная длина сообщения
    max_length: 90
    # Стоимость
    cost: 0

    # Сообщения
    messages:
      usage: "&eИспользуйте: /bc [текст]"
      insufficient_funds: "&fНа вашем балансе недостаточно монет!"
      payment_success: "&fС вашего баланса было списано {count} монет!"

    # Шаблон сообщения для рассылки
    broadcast_template:
      - "&c"
      - "&c &7[#ff4242ОБЪЯВЛЕНИЕ&7] &fАвтор: &b%player%"
      - "&c &fТекст &7» &c%message%"
      - "&c"

    # Настройки звука
    sound:
      enabled: true
      type: "BLOCK_NOTE_BLOCK_HAT"
      volume: 0.7
      pitch: 1.0

  ad:

    permission: "ney_broadcast.ad"
    max_length: 90
    cost: 1500

    messages:
      usage: "&eИспользуйте: /ad [текст]"
      insufficient_funds: "&fНа вашем балансе недостаточно монет!"
      payment_success: "&fС вашего баланса было списано {count} монет!"

    broadcast_template:
      - "&c"
      - "&c &7[#63ffefРЕКЛАМА&7] &fАвтор: &b%player%"
      - "&c &fТекст &7» &c%message%"
      - "&c"

    sound:
      enabled: true
      type: "BLOCK_NOTE_BLOCK_HAT"
      volume: 0.7
      pitch: 1.0

  buy:

    permission: "ney_broadcast.buy"
    max_length: 90
    cost: 2000

    messages:
      usage: "&eИспользуйте: /buy [текст]"
      insufficient_funds: "&fНа вашем балансе недостаточно монет!"
      payment_success: "&fС вашего баланса было списано {count} монет!"

    broadcast_template:
      - "&c"
      - "&c &7[#8642fcПОКУПКА&7] &fАвтор: &b%player%"
      - "&c &fТекст &7» &c%message%"
      - "&c"

    sound:
      enabled: true
      type: "BLOCK_NOTE_BLOCK_HAT"
      volume: 0.7
      pitch: 1.0