name: NeyBroadcast
version: '1.0.2'
main: com.ney.broadcast.NeyBroadcast
api-version: 1.13
commands:
  ad:
    description: Send an advertisement message to all players
    usage: /<command> <message>
    aliases: [advertising]
  bc:
    description: Send a global broadcast message
    usage: /<command> <message>
    aliases: [broadcast]
  buy:
    description: Announce a purchase message to all players
    usage: /<command> <message>